version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: causeconnect-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - causeconnect-network

  neo4j:
    image: neo4j:5.20
    container_name: causeconnect-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_PLUGINS: ${NEO4J_PLUGINS}
    ports:
      - "${NEO4J_WEB_UI_PORT}:7474"
      - "${NEO4J_APP_PORT}:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - causeconnect-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: causeconnect-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - "2181:2181"
    networks:
      - causeconnect-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: causeconnect-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
    networks:
      - causeconnect-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: causeconnect-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - neo4j
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_NEO4J_URI: ${SPRING_NEO4J_URI}
      SPRING_NEO4J_AUTHENTICATION_USERNAME: ${SPRING_NEO4J_AUTHENTICATION_USERNAME}
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: ${SPRING_NEO4J_AUTHENTICATION_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    networks:
      - causeconnect-network

volumes:
  postgres_data:
  neo4j_data:

networks:
  causeconnect-network:
    driver: bridge
